#!/usr/bin/env bash
# Bash script to ping an IP address passed as an argument

# check if the script is called with an argument
if [$# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
